```{r setup,include=FALSE}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(tableone)
library(table1)
library(ggpubr)
library(stargazer)
library(Hmisc)
library(cowplot)
```

import data
```{r}
data<-read_csv("data.csv",
               col_types = "dccddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd"
               )
```




```{r}
data$诊断分类=as.factor(data$诊断分类)

data$DD变化 <- data$术后24小时DD-data$术前DD
```


```{r}
#average
data <- mutate(data,ALT=ifelse(is.na(术前ALT),术后24小时ALT,
                               ifelse(is.na(术后24小时ALT),术前ALT,(术前ALT+术后24小时ALT)/2))
               )

data <- mutate(data,AST=ifelse(is.na(术前AST),术后24小时AST,
                               ifelse(is.na(术后24小时AST),术前AST,(术前AST+术后24小时AST)/2))
               )

data <- mutate(data,Alb=ifelse(is.na(术前Alb),术后24小时Alb,
                               ifelse(is.na(术后24小时Alb),术前Alb,(术前Alb+术后24小时Alb)/2))
               )

data <- mutate(data,高密度脂蛋白=ifelse(is.na(术前高密度脂蛋白),术后24小时高密度脂蛋白,
                               ifelse(is.na(术后24小时高密度脂蛋白),术前高密度脂蛋白,(术前高密度脂蛋白+术后24小时高密度脂蛋白)/2))
               )

data <- mutate(data,低密度脂蛋白=ifelse(is.na(术前低密度脂蛋白),术后24小时低密度脂蛋白,
                               ifelse(is.na(术后24小时低密度脂蛋白),术前低密度脂蛋白,(术前低密度脂蛋白+术后24小时低密度脂蛋白)/2))
               )

data <- mutate(data,TG=ifelse(is.na(术前TG),术后24小时TG,
                               ifelse(is.na(术后24小时TG),术前TG,(术前TG+术后24小时TG)/2))
               )

data <- mutate(data,TC=ifelse(is.na(术前TC),术后24小时TC,
                               ifelse(is.na(术后24小时TC),术前TC,(术前TC+术后24小时TC)/2))
               )


data <- mutate(data,Glu=ifelse(is.na(术前Glu),术后24小时Glu,
                               ifelse(is.na(术后24小时Glu),术前Glu,(术前Glu+术后24小时Glu)/2))
               )

data <- mutate(data,Ucr=ifelse(is.na(术前Ucr),术后24小时Ucr,
                               ifelse(is.na(术后24小时Ucr),术前Ucr,(术前Ucr+术后24小时Ucr)/2))
               )
data <- mutate(data,BUN=ifelse(is.na(术前BUN),术后24小时BUN,
                               ifelse(is.na(术后24小时BUN),术前BUN,(术前BUN+术后24小时BUN)/2))
               )
```


```{r}
#variables
myVars <- c("诊断分类", "年龄", "身高", 
            "体重", "BMI", "术前PT", "术后24小时PT", "术前APTT", "术后24小时APTT", 
            "术前TT", "术后24小时TT", "术前FIB", "术后24小时FIB", "术前DD", 
            "术后24小时DD", "DD变化","术前FDP", "术后24小时FDP", "术前INR", "术后24小时INR", 
            "术前PLT", "术后24小时PLT", "术前WBC", "术后24小时WBC", "术前NBC", 
            "术后24小时NBC", "术前Npct", "术后24小时NPct", "术前RBC", "术后24小时RBC", 
            "术前Hb", "术后24小时Hb", "术前RBCpct", "术后24小时RBCpct", "ALT", 
            "AST", "Alb",  
            "高密度脂蛋白","低密度脂蛋白", 
            "TG", "TC", 
            "Glu", "Ucr", 
            "BUN", "输出总能量", "HIFU照射总时间", "估计治疗体积", 
            "治疗时间", "平均功率", "治疗强度", "能效因子")

#categorical variables
catVars <- c("诊断分类")

# nonnormal variables
nonnormalvars <- c( "术前PT", "术后24小时PT", "术前APTT", "术后24小时APTT", 
            "术前TT", "术后24小时TT", "术前FIB", "术后24小时FIB", "术前DD", 
            "术后24小时DD", "DD变化","术前FDP", "术后24小时FDP", "术前INR", "术后24小时INR", 
            "术前PLT", "术后24小时PLT", "术前WBC", "术后24小时WBC", "术前NBC", 
            "术后24小时NBC", "术前Npct", "术后24小时NPct", "术前RBC", "术后24小时RBC", 
            "术前Hb", "术后24小时Hb", "术前RBCpct", "术后24小时RBCpct", "ALT", 
            "AST", "Alb",  
            "高密度脂蛋白","低密度脂蛋白", 
            "TG", "TC", 
            "Glu", "Ucr", 
            "BUN", "输出总能量", "HIFU照射总时间", "估计治疗体积", 
            "治疗时间", "平均功率", "治疗强度", "能效因子")

# table 1
tab <- CreateTableOne(vars = myVars, strata ="诊断分类", data = data, factorVars =catVars,addOverall = TRUE)
myTable<-print(tab,
               #nonnormal=nonnormalvars,
               showAllLevels = TRUE)


# save
#write.csv(myTable, file = "myTable.csv")
```






```{r}
#DD & FDP
data <- mutate(data,DD_FDPgroup=ifelse(data$术后24小时FDP>5 & data$术后24小时DD>1,1,0))

#DD
#data <- mutate(data,DD_FDPgroup=ifelse(data$术后24小时DD>1,1,0))

#FDP
#data <- mutate(data,DD_FDPgroup=ifelse(data$术后24小时FDP>5,1,0))

data$DD_FDPgroup <- as.factor(data$DD_FDPgroup)
```





```{r}
#Exposure energy (KJ)
data$输出总能量<-data$输出总能量/1000

q1 <- quantile(data$输出总能量,1/3,na.rm=T)
q2 <- quantile(data$输出总能量,2/3,na.rm=T)
data <- mutate(data,能量group=ifelse(data$输出总能量<=q1,1,ifelse(data$输出总能量<=q2,2,3)))
data$能量group <- as.factor(data$能量group)
```



```{r}
model <- glm(DD_FDPgroup~能量group
             +年龄+BMI
             +术前PLT+术前Hb+术前AST+术前Alb+术前TG+术前Ucr+术前DD
             ,data=data, family='binomial')

lg <- ShowRegTable(model, digits = 2)

```


```{r}
#Sonication time (s)
q1 <- quantile(data$HIFU照射总时间,1/3,na.rm=T)
q2 <- quantile(data$HIFU照射总时间,2/3,na.rm=T)
data <- mutate(data,HIFU照射总时间group=ifelse(data$HIFU照射总时间<=q1,1,ifelse(data$HIFU照射总时间<=q2,2,3)))
data$HIFU照射总时间group <- as.factor(data$HIFU照射总时间group)
```



```{r}
model <- glm(DD_FDPgroup~HIFU照射总时间group
             +年龄+BMI
             +术前PLT+术前Hb+术前AST+术前Alb+术前TG+术前Ucr+术前DD
             ,data=data, family='binomial')

lg <- ShowRegTable(model, digits = 2)

```






```{r}
#Treatment volume (cm3)
q1 <- quantile(data$估计治疗体积,1/3,na.rm=T)
q2 <- quantile(data$估计治疗体积,2/3,na.rm=T)
data <- mutate(data,估计治疗体积group=ifelse(data$估计治疗体积<=q1,1,ifelse(data$估计治疗体积<=q2,2,3)))
data$估计治疗体积group <- as.factor(data$估计治疗体积group)
```




```{r}
model <- glm(DD_FDPgroup~估计治疗体积group
             +年龄+BMI
             +术前PLT+术前Hb+术前AST+术前Alb+术前TG+术前Ucr+术前DD
             ,data=data, family='binomial')

lg <- ShowRegTable(model, digits = 2)

```


```{r}
#Treatment time (min)
q1 <- quantile(data$治疗时间,1/3,na.rm=T)
q2 <- quantile(data$治疗时间,2/3,na.rm=T)
data <- mutate(data,治疗时间group=ifelse(data$治疗时间<=q1,1,ifelse(data$治疗时间<=q2,2,3)))
data$治疗时间group <- as.factor(data$治疗时间group)
```



```{r}
model <- glm(DD_FDPgroup~治疗时间group
             +年龄+BMI
             +术前PLT+术前Hb+术前AST+术前Alb+术前TG+术前Ucr+术前DD
             ,data=data, family='binomial')

lg <- ShowRegTable(model, digits = 2)

```



```{r}
#Power (W)
q1 <- quantile(data$平均功率,1/3,na.rm=T)
q2 <- quantile(data$平均功率,2/3,na.rm=T)
data <- mutate(data,平均功率group=ifelse(data$平均功率<=q1,1,ifelse(data$平均功率<=q2,2,3)))
data$平均功率group <- as.factor(data$平均功率group)
```



```{r}
model <- glm(DD_FDPgroup~平均功率group
             +年龄+BMI
             +术前PLT+术前Hb+术前AST+术前Alb+术前TG+术前Ucr+术前DD
             ,data=data, family='binomial')

lg <- ShowRegTable(model, digits = 2)

```




```{r}
#Therapeutic intensity (s/h)
q1 <- quantile(data$治疗强度,1/3,na.rm=T)
q2 <- quantile(data$治疗强度,2/3,na.rm=T)
data <- mutate(data,治疗强度group=ifelse(data$治疗强度<=q1,1,ifelse(data$治疗强度<=q2,2,3)))
data$治疗强度group <- as.factor(data$治疗强度group)
```



```{r}
model <- glm(DD_FDPgroup~治疗强度group
             +年龄+BMI
             +术前PLT+术前Hb+术前AST+术前Alb+术前TG+术前Ucr+术前DD
             ,data=data, family='binomial')

lg <- ShowRegTable(model, digits = 2)

```


```{r}
#Energy efficiency factor(J/mm3)
q1 <- quantile(data$能效因子,1/3,na.rm=T)
q2 <- quantile(data$能效因子,2/3,na.rm=T)
data <- mutate(data,能效因子group=ifelse(data$能效因子<=q1,1,ifelse(data$能效因子<=q2,2,3)))
data$能效因子group <- as.factor(data$能效因子group)
```



```{r}
model <- glm(DD_FDPgroup~能效因子group
             +年龄+BMI
             +术前PLT+术前Hb+术前AST+术前Alb+术前TG+术前Ucr+术前DD
             ,data=data, family='binomial')

lg <- ShowRegTable(model, digits = 2)

```


